#!/usr/bin/env python3
"""
Complete loader for ALL 753 municipalities in Nepal
Based on official data from the Government of Nepal
"""

import os
import sys
import django

# Setup Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'nepal_election_app.settings')
django.setup()

from locations.models import Province, District, Municipality
from django.db import transaction

# Complete municipality data for ALL 77 districts and 753 municipalities
COMPLETE_MUNICIPALITY_DATA = {
    # ========== KOSHI PROVINCE (Province 1) ==========
    "Bhojpur": [
        ("Bhojpur", "भोजपुर", "municipality", 10),
        ("Shadanand", "षडानन्द", "municipality", 9),
        ("Tyamkemaiyum", "ट्याम्केमैयुम", "rural_municipality", 6),
        ("Ramprasad Rai", "रामप्रसाद राई", "rural_municipality", 5),
        ("Arun", "अरुण", "rural_municipality", 9),
        ("Pauwadungma", "पौवादुङमा", "rural_municipality", 5),
        ("Salpasilichho", "साल्पासिलिछो", "rural_municipality", 6),
        ("Aamchok", "आमचोक", "rural_municipality", 7),
        ("Hatuwagadhi", "हतुवागढी", "rural_municipality", 6),
    ],
    "Dhankuta": [
        ("Dhankuta", "धनकुटा", "municipality", 10),
        ("Pakhribas", "पाख्रिबास", "municipality", 9),
        ("Mahalaxmi", "महालक्ष्मी", "municipality", 11),
        ("Sangurigadhi", "सागुरीगढी", "rural_municipality", 7),
        ("Khalsa Chhintang Sahidbhumi", "खाल्सा छिन्ताङ", "rural_municipality", 6),
        ("Chaubise", "चौबिसे", "rural_municipality", 9),
        ("Chhathar Jorpati", "छथर जोरपाटी", "rural_municipality", 8),
    ],
    "Ilam": [
        ("Ilam", "इलाम", "municipality", 12),
        ("Deumai", "देउमाई", "municipality", 10),
        ("Mai", "माई", "municipality", 10),
        ("Suryodaya", "सूर्योदय", "municipality", 12),
        ("Chulachuli", "चुलाचुली", "rural_municipality", 9),
        ("Rong", "रोङ", "rural_municipality", 6),
        ("Mangsebung", "माङसेबुङ", "rural_municipality", 9),
        ("Sandakpur", "सन्दकपुर", "rural_municipality", 5),
        ("Fakfokthum", "फाकफोकथुम", "rural_municipality", 9),
        ("Maijogmai", "माईजोगमाई", "rural_municipality", 6),
    ],
    "Jhapa": [
        ("Mechinagar", "मेचीनगर", "municipality", 15),
        ("Damak", "दमक", "municipality", 10),
        ("Kankai", "कनकाई", "municipality", 12),
        ("Bhadrapur", "भद्रपुर", "municipality", 10),
        ("Arjundhara", "अर्जुनधारा", "municipality", 12),
        ("Shivasatakshi", "शिवसताक्षी", "municipality", 13),
        ("Gauradaha", "गौरादह", "municipality", 11),
        ("Birtamode", "बिर्तामोड", "municipality", 9),
        ("Kamal", "कमल", "rural_municipality", 8),
        ("Jhapa", "झापा", "rural_municipality", 8),
        ("Buddhashanti", "बुद्धशान्ति", "rural_municipality", 7),
        ("Haldibari", "हल्दीबारी", "rural_municipality", 7),
        ("Kachankawal", "कचनकवल", "rural_municipality", 10),
        ("Barhadashi", "बाह्रदशी", "rural_municipality", 6),
        ("Gaurigunj", "गौरीगंज", "rural_municipality", 5),
    ],
    "Khotang": [
        ("Halesi Tuwachung", "हलेसी तुवाचुङ", "municipality", 11),
        ("Diprung Chuichumma", "दिप्रुङ चुइचुम्मा", "rural_municipality", 7),
        ("Aiselukharka", "ऐसेलुखर्क", "rural_municipality", 7),
        ("Lamidanda", "लामीडाँडा", "rural_municipality", 5),
        ("Jantedhunga", "जन्तेढुंगा", "rural_municipality", 5),
        ("Khotehang", "खोटेहाङ", "rural_municipality", 9),
        ("Kepilasgadhi", "केपिलासगढी", "rural_municipality", 5),
        ("Barahpokhari", "बराहपोखरी", "rural_municipality", 7),
        ("Rawabesi", "रावाबेसी", "rural_municipality", 9),
        ("Sakela", "साकेला", "rural_municipality", 9),
    ],
    "Morang": [
        ("Biratnagar", "विराटनगर", "metropolitan", 19),
        ("Sundar Haraicha", "सुन्दर हरैचा", "municipality", 14),
        ("Rangeli", "रंगेली", "municipality", 9),
        ("Pathari-Sanischare", "पथरी-शनिश्चरे", "municipality", 9),
        ("Urlabari", "उर्लाबारी", "municipality", 12),
        ("Belbari", "बेलबारी", "municipality", 10),
        ("Letang", "लेटाङ", "municipality", 11),
        ("Ratuwamai", "रतुवामाई", "municipality", 9),
        ("Sunawarshi", "सुनवर्षी", "rural_municipality", 9),
        ("Dhanpalthan", "धनपालथान", "rural_municipality", 6),
        ("Budhiganga", "बुढीगंगा", "rural_municipality", 8),
        ("Gramthan", "ग्रामथान", "rural_municipality", 6),
        ("Katahari", "कटहरी", "rural_municipality", 9),
        ("Kerabari", "केराबारी", "rural_municipality", 9),
        ("Miklajung", "मिक्लाजुङ", "rural_municipality", 9),
        ("Kanepokhari", "कानेपोखरी", "rural_municipality", 7),
        ("Jahada", "जहदा", "rural_municipality", 6),
    ],
    "Okhaldhunga": [
        ("Siddhicharan", "सिद्धिचरण", "municipality", 9),
        ("Champadevi", "चम्पादेवी", "rural_municipality", 9),
        ("Chisankhugadhi", "चिसंखुगढी", "rural_municipality", 9),
        ("Khijidemba", "खिजिदेम्बा", "rural_municipality", 9),
        ("Likhu", "लिखु", "rural_municipality", 9),
        ("Manebhanjyang", "मानेभञ्ज्याङ", "rural_municipality", 9),
        ("Molung", "मोलुङ", "rural_municipality", 9),
        ("Sunkoshi", "सुनकोशी", "rural_municipality", 8),
    ],
    "Panchthar": [
        ("Phidim", "फिदिम", "municipality", 9),
        ("Falgunanda", "फाल्गुनन्द", "rural_municipality", 9),
        ("Hilihang", "हिलिहाङ", "rural_municipality", 9),
        ("Kummayak", "कुम्मायक", "rural_municipality", 9),
        ("Miklajung", "मिक्लाजुङ", "rural_municipality", 9),
        ("Phalelung", "फालेलुङ", "rural_municipality", 9),
        ("Tumbewa", "तुम्बेवा", "rural_municipality", 9),
        ("Yangwarak", "याङवरक", "rural_municipality", 9),
    ],
    "Sankhuwasabha": [
        ("Chainpur", "चैनपुर", "municipality", 10),
        ("Khandbari", "खाँदबारी", "municipality", 11),
        ("Panchkhapan", "पाँचखपन", "municipality", 9),
        ("Madi", "मादी", "municipality", 9),
        ("Dharmadevi", "धर्मदेवी", "municipality", 10),
        ("Bhotkhola", "भोटखोला", "rural_municipality", 5),
        ("Chichila", "चिचिला", "rural_municipality", 5),
        ("Makalu", "मकालु", "rural_municipality", 6),
        ("Savapokhari", "सभापोखरी", "rural_municipality", 6),
        ("Silichong", "सिलीचोङ", "rural_municipality", 5),
    ],
    "Solukhumbu": [
        ("Solududhkunda", "सोलुदुधकुण्ड", "municipality", 11),
        ("Dudhkoshi", "दुधकोशी", "rural_municipality", 9),
        ("Khumbu Pasanglhamu", "खुम्बु पासाङल्हामु", "rural_municipality", 5),
        ("Likhu Pike", "लिखु पिके", "rural_municipality", 5),
        ("Mahakulung", "महाकुलुङ", "rural_municipality", 6),
        ("Necha Salyan", "नेचासल्यान", "rural_municipality", 5),
        ("Sotang", "सोताङ", "rural_municipality", 5),
        ("Thulung Dudhkoshi", "थुलुङ दुधकोशी", "rural_municipality", 9),
    ],
    "Sunsari": [
        ("Itahari", "इटहरी", "sub_metropolitan", 20),
        ("Dharan", "धरान", "sub_metropolitan", 20),
        ("Inaruwa", "इनरुवा", "municipality", 12),
        ("Duhabi", "दुहबी", "municipality", 13),
        ("Ramdhuni", "रामधुनी", "municipality", 9),
        ("Barahachhetra", "बराहक्षेत्र", "municipality", 11),
        ("Koshi", "कोशी", "rural_municipality", 8),
        ("Gadhi", "गढी", "rural_municipality", 7),
        ("Barju", "बर्जु", "rural_municipality", 6),
        ("Bhokraha Narsingh", "भोक्राहा नरसिंह", "rural_municipality", 6),
        ("Harinagara", "हरिनगर", "rural_municipality", 7),
        ("Dewanganj", "देवानगंज", "rural_municipality", 6),
    ],
    "Taplejung": [
        ("Phungling", "फुङलिङ", "municipality", 11),
        ("Aathrai Triveni", "आठराई त्रिवेणी", "rural_municipality", 5),
        ("Meringden", "मेरिङदेन", "rural_municipality", 6),
        ("Mikwakhola", "मिक्वाखोला", "rural_municipality", 5),
        ("Pathibhara Yangwarak", "पाथिभरा याङवरक", "rural_municipality", 6),
        ("Phaktanglung", "फक्ताङलुङ", "rural_municipality", 7),
        ("Sidingwa", "सिदिङ्वा", "rural_municipality", 6),
        ("Sirijangha", "सिरिजङ्घा", "rural_municipality", 8),
        ("Maiwakhola", "मैवाखोला", "rural_municipality", 6),
    ],
    "Terhathum": [
        ("Myanglung", "म्याङलुङ", "municipality", 10),
        ("Laligurans", "लालीगुराँस", "municipality", 9),
        ("Aathrai", "आठराई", "rural_municipality", 6),
        ("Chhathar", "छथर", "rural_municipality", 6),
        ("Menchayam", "मेन्छयायेम", "rural_municipality", 6),
        ("Phedap", "फेदाप", "rural_municipality", 5),
    ],
    "Udayapur": [
        ("Triyuga", "त्रियुगा", "municipality", 16),
        ("Katari", "कटारी", "municipality", 14),
        ("Chaudandigadhi", "चौदण्डीगढी", "municipality", 10),
        ("Belaka", "बेलका", "municipality", 9),
        ("Rautamai", "रौतामाई", "rural_municipality", 8),
        ("Limchungbung", "लिम्चुङबुङ", "rural_municipality", 7),
        ("Tapli", "ताप्ली", "rural_municipality", 5),
        ("Udayapurgadhi", "उदयपुरगढी", "rural_municipality", 8),
    ],
    
    # ========== MADHESH PROVINCE ==========
    "Bara": [
        ("Kalaiya", "कलैया", "sub_metropolitan", 24),
        ("Jeetpur Simara", "जीतपुर सिमरा", "sub_metropolitan", 24),
        ("Kolhabi", "कोल्हवी", "municipality", 11),
        ("Nijgadh", "निजगढ", "municipality", 13),
        ("Mahagadhimai", "महागढीमाई", "municipality", 11),
        ("Simraungadh", "सिम्रौनगढ", "municipality", 11),
        ("Pachrauta", "पचरौता", "municipality", 9),
        ("Adarsh Kotwal", "आदर्श कोटवाल", "rural_municipality", 8),
        ("Baragadhi", "बारागढी", "rural_municipality", 5),
        ("Bishrampur", "विश्रामपुर", "rural_municipality", 5),
        ("Devtal", "देवताल", "rural_municipality", 5),
        ("Karaiyamai", "करैयामाई", "rural_municipality", 5),
        ("Parwanipur", "परवानीपुर", "rural_municipality", 5),
        ("Pheta", "फेटा", "rural_municipality", 5),
        ("Prasauni", "प्रसौनी", "rural_municipality", 5),
        ("Suvarna", "सुवर्ण", "rural_municipality", 5),
    ],
    "Dhanusha": [
        ("Janakpur", "जनकपुर", "sub_metropolitan", 25),
        ("Chhireshwarnath", "क्षिरेश्वरनाथ", "municipality", 16),
        ("Ganeshman Charnath", "गणेशमान चारनाथ", "municipality", 12),
        ("Dhanusadham", "धनुषाधाम", "municipality", 10),
        ("Nagarain", "नगराइन", "municipality", 12),
        ("Bideha", "विदेह", "municipality", 9),
        ("Mithila", "मिथिला", "municipality", 12),
        ("Sahidnagar", "शहीदनगर", "municipality", 17),
        ("Sabaila", "सबैला", "municipality", 22),
        ("Kamala", "कमला", "municipality", 12),
        ("Mithila Bihari", "मिथिला बिहारी", "municipality", 19),
        ("Hansapur", "हंसपुर", "municipality", 9),
        ("Janak Nandani", "जनक नन्दनी", "rural_municipality", 9),
        ("Bateshwar", "बटेश्वर", "rural_municipality", 9),
        ("Mukhiyapatti Musaharmiya", "मुखियापट्टी मुसहरमिया", "rural_municipality", 9),
        ("Lakshminya", "लक्ष्मीन्या", "rural_municipality", 9),
        ("Aurahi", "औरही", "rural_municipality", 9),
        ("Dhanauji", "धनौजी", "rural_municipality", 9),
    ],
    "Mahottari": [
        ("Jaleshwar", "जलेश्वर", "municipality", 17),
        ("Bardibas", "बर्दिबास", "municipality", 19),
        ("Gaushala", "गौशाला", "municipality", 14),
        ("Loharpatti", "लोहरपट्टी", "municipality", 9),
        ("Bhangaha", "भंगहा", "municipality", 15),
        ("Balawa", "बलवा", "municipality", 11),
        ("Matihani", "मतिहानी", "municipality", 19),
        ("Manara Shiswa", "मनरा शिसवा", "municipality", 9),
        ("Aurahi", "औरही", "rural_municipality", 9),
        ("Ekdara", "एकडारा", "rural_municipality", 9),
        ("Mahottari", "महोत्तरी", "rural_municipality", 9),
        ("Pipra", "पिपरा", "rural_municipality", 9),
        ("Samsi", "साम्सी", "rural_municipality", 6),
        ("Sonama", "सोनमा", "rural_municipality", 8),
        ("Ram Gopalpur", "राम गोपालपुर", "municipality", 9),
    ],
    "Parsa": [
        ("Birgunj", "वीरगंज", "metropolitan", 32),
        ("Pokhariya", "पोखरिया", "municipality", 10),
        ("Parsagadhi", "पर्सागढी", "municipality", 9),
        ("Bahudarmai", "बहुदरमाई", "municipality", 9),
        ("Thori", "ठोरी", "rural_municipality", 5),
        ("Bindabasini", "बिन्दबासिनी", "rural_municipality", 5),
        ("Dhobini", "धोबिनी", "rural_municipality", 5),
        ("Chhipaharmai", "छिपहरमाई", "rural_municipality", 5),
        ("Jagarnathpur", "जगरनाथपुर", "rural_municipality", 5),
        ("Jirabhawani", "जिरा भवानी", "rural_municipality", 5),
        ("Kalikamai", "कालिकामाई", "rural_municipality", 5),
        ("Pakaha Mainpur", "पकाहा मैनपुर", "rural_municipality", 5),
        ("Paterwa Sugauli", "पटेर्वा सुगौली", "rural_municipality", 5),
        ("Sakhuwa Prasauni", "सखुवा प्रसौनी", "rural_municipality", 6),
    ],
    "Rautahat": [
        ("Chandrapur", "चन्द्रपुर", "municipality", 10),
        ("Garuda", "गरुडा", "municipality", 9),
        ("Gaur", "गौर", "municipality", 9),
        ("Baudhimai", "बौधीमाई", "municipality", 9),
        ("Brindaban", "बृन्दावन", "municipality", 9),
        ("Devahi Gonahi", "देवाही गोनाही", "municipality", 9),
        ("Gadhimai", "गढीमाई", "municipality", 9),
        ("Gujara", "गुजरा", "municipality", 9),
        ("Ishanath", "ईशनाथ", "municipality", 9),
        ("Katahariya", "कटहरिया", "municipality", 9),
        ("Madhav Narayan", "माधव नारायण", "municipality", 9),
        ("Maulapur", "मौलापुर", "municipality", 9),
        ("Paroha", "परोहा", "municipality", 9),
        ("Phatuwa Bijayapur", "फतुवा बिजयपुर", "municipality", 9),
        ("Rajdevi", "राजदेवी", "municipality", 9),
        ("Rajpur", "राजपुर", "municipality", 9),
        ("Durga Bhagwati", "दुर्गा भगवती", "rural_municipality", 5),
        ("Yamunamai", "यमुनामाई", "rural_municipality", 5),
    ],
    "Saptari": [
        ("Rajbiraj", "राजविराज", "municipality", 16),
        ("Kanchanrup", "कञ्चनरुप", "municipality", 11),
        ("Dakneshwori", "डाक्नेश्वरी", "municipality", 11),
        ("Bodebarsain", "बोदे बरसाईन", "municipality", 14),
        ("Saptakoshi", "सप्तकोशी", "municipality", 11),
        ("Khadak", "खडक", "municipality", 11),
        ("Hanumannagar Kankalini", "हनुमाननगर कंकालिनी", "municipality", 14),
        ("Shambhunath", "शम्भुनाथ", "municipality", 11),
        ("Surunga", "सुरुङ्गा", "municipality", 11),
        ("Agnisair Krishna Savaran", "अग्निसाइर कृष्णासवरन", "rural_municipality", 6),
        ("Balan-Bihul", "बलान-बिहुल", "rural_municipality", 5),
        ("Bishnupur", "विष्णुपुर", "rural_municipality", 7),
        ("Chhinnamasta", "छिन्नमस्ता", "rural_municipality", 7),
        ("Mahadeva", "महादेवा", "rural_municipality", 5),
        ("Rupani", "रुपनी", "rural_municipality", 6),
        ("Tilathi Koiladi", "तिलाठी कोइलाडी", "rural_municipality", 8),
        ("Tirhut", "तिरहुत", "rural_municipality", 5),
    ],
    "Sarlahi": [
        ("Ishwarpur", "ईश्वरपुर", "municipality", 16),
        ("Malangwa", "मलंगवा", "municipality", 16),
        ("Lalbandi", "लालबन्दी", "municipality", 17),
        ("Haripur", "हरिपुर", "municipality", 11),
        ("Haripurwa", "हरिपुर्वा", "municipality", 10),
        ("Hariwan", "हरिवन", "municipality", 11),
        ("Barahathwa", "बरहथवा", "municipality", 18),
        ("Balara", "बलरा", "municipality", 11),
        ("Godaita", "गोडैता", "municipality", 12),
        ("Bagmati", "बागमती", "municipality", 12),
        ("Kabilasi", "कविलासी", "municipality", 10),
        ("Basbariya", "बसबरिया", "rural_municipality", 5),
        ("Bishnu", "विष्णु", "rural_municipality", 5),
        ("Brahampuri", "ब्रह्मपुरी", "rural_municipality", 5),
        ("Chakraghatta", "चक्रघट्टा", "rural_municipality", 5),
        ("Chandranagar", "चन्द्रनगर", "rural_municipality", 5),
        ("Dhankaul", "धनकौल", "rural_municipality", 5),
        ("Kaudena", "कौडेना", "rural_municipality", 5),
        ("Parsa", "पर्सा", "rural_municipality", 5),
    ],
    "Siraha": [
        ("Lahan", "लहान", "municipality", 24),
        ("Dhangadhimai", "धनगढीमाई", "municipality", 14),
        ("Siraha", "सिराहा", "municipality", 22),
        ("Golbazar", "गोलबजार", "municipality", 13),
        ("Mirchaiya", "मिर्चैया", "municipality", 12),
        ("Kalyanpur", "कल्याणपुर", "municipality", 12),
        ("Karjanha", "कर्जन्हा", "municipality", 9),
        ("Sukhipur", "सुखीपुर", "municipality", 10),
        ("Arnama", "अर्नमा", "rural_municipality", 7),
        ("Aurahi", "औरही", "rural_municipality", 5),
        ("Bariyarpatti", "बरियारपट्टी", "rural_municipality", 5),
        ("Bhagwanpur", "भगवानपुर", "rural_municipality", 5),
        ("Bishnupur", "विष्णुपुर", "rural_municipality", 5),
        ("Lakshmipur Patari", "लक्ष्मीपुर पतारी", "rural_municipality", 6),
        ("Naraha", "नरहा", "rural_municipality", 5),
        ("Nawarajpur", "नवराजपुर", "rural_municipality", 5),
        ("Sakhuwa Nankarkatti", "सखुवा नान्कारकट्टी", "rural_municipality", 5),
    ],
    
    # ========== BAGMATI PROVINCE ==========
    "Bhaktapur": [
        ("Bhaktapur", "भक्तपुर", "municipality", 10),
        ("Changunarayan", "चाँगुनारायण", "municipality", 9),
        ("Madhyapur Thimi", "मध्यपुर थिमी", "municipality", 9),
        ("Suryabinayak", "सूर्यविनायक", "municipality", 10),
    ],
    "Chitwan": [
        ("Bharatpur", "भरतपुर", "metropolitan", 29),
        ("Kalika", "कालिका", "municipality", 11),
        ("Khairahani", "खैरहनी", "municipality", 13),
        ("Madi", "माडी", "municipality", 9),
        ("Ratnanagar", "रत्ननगर", "municipality", 16),
        ("Rapti", "राप्ती", "municipality", 13),
        ("Ichchhakamana", "इच्छाकामना", "rural_municipality", 7),
    ],
    "Dhading": [
        ("Dhunibeshi", "धुनीबेंशी", "municipality", 9),
        ("Nilkantha", "नीलकण्ठ", "municipality", 14),
        ("Khaniyabas", "खनियाबास", "rural_municipality", 5),
        ("Gajuri", "गजुरी", "rural_municipality", 8),
        ("Galchhi", "गल्छी", "rural_municipality", 8),
        ("Gangajamuna", "गंगाजमुना", "rural_municipality", 7),
        ("Jwalamukhi", "ज्वालामूखी", "rural_municipality", 7),
        ("Thakre", "थाक्रे", "rural_municipality", 11),
        ("Netrawati Dabjong", "नेत्रावती डबजोङ", "rural_municipality", 5),
        ("Benighat Rorang", "बेनीघाट रोराङ्ग", "rural_municipality", 10),
        ("Ruby Valley", "रुबी भ्याली", "rural_municipality", 6),
        ("Siddhalek", "सिद्धलेक", "rural_municipality", 7),
        ("Tripurasundari", "त्रिपुरासुन्दरी", "rural_municipality", 6),
    ],
    "Dolakha": [
        ("Bhimeshwar", "भीमेश्वर", "municipality", 9),
        ("Jiri", "जिरी", "municipality", 9),
        ("Bigu", "बिगु", "rural_municipality", 8),
        ("Gaurishankar", "गौरीशंकर", "rural_municipality", 9),
        ("Kalinchok", "कालिन्चोक", "rural_municipality", 9),
        ("Melung", "मेलुङ", "rural_municipality", 7),
        ("Sailung", "शैलुङ", "rural_municipality", 8),
        ("Tamakoshi", "तामाकोशी", "rural_municipality", 7),
        ("Baiteshwar", "बैतेश्वर", "rural_municipality", 5),
    ],
    "Kathmandu": [
        ("Kathmandu", "काठमाडौं", "metropolitan", 32),
        ("Budhanilkantha", "बूढानीलकण्ठ", "municipality", 13),
        ("Chandragiri", "चन्द्रागिरी", "municipality", 15),
        ("Dakshinkali", "दक्षिणकाली", "municipality", 9),
        ("Gokarneshwar", "गोकर्णेश्वर", "municipality", 9),
        ("Kageshwari Manohara", "कागेश्वरी मनोहरा", "municipality", 9),
        ("Kirtipur", "कीर्तिपुर", "municipality", 10),
        ("Nagarjun", "नागार्जुन", "municipality", 10),
        ("Shankharapur", "शंखरापुर", "municipality", 9),
        ("Tarakeshwar", "तारकेश्वर", "municipality", 11),
        ("Tokha", "टोखा", "municipality", 11),
    ],
    "Kavrepalanchok": [
        ("Dhulikhel", "धुलिखेल", "municipality", 12),
        ("Banepa", "बनेपा", "municipality", 14),
        ("Panauti", "पनौती", "municipality", 12),
        ("Panchkhal", "पाँचखाल", "municipality", 13),
        ("Namobuddha", "नमोबुद्ध", "municipality", 11),
        ("Mandandeupur", "मण्डनदेउपुर", "municipality", 12),
        ("Bethanchok", "बेथानचोक", "rural_municipality", 6),
        ("Chaurideurali", "चौंरीदेउराली", "rural_municipality", 9),
        ("Khanikhola", "खानीखोला", "rural_municipality", 7),
        ("Mahabharat", "महाभारत", "rural_municipality", 8),
        ("Roshi", "रोशी", "rural_municipality", 12),
        ("Temal", "तेमाल", "rural_municipality", 9),
        ("Bhumlu", "भुम्लु", "rural_municipality", 10),
    ],
    "Lalitpur": [
        ("Lalitpur", "ललितपुर", "metropolitan", 29),
        ("Godawari", "गोदावरी", "municipality", 14),
        ("Mahalaxmi", "महालक्ष्मी", "municipality", 10),
        ("Konjyosom", "कोन्ज्योसोम", "rural_municipality", 5),
        ("Bagmati", "बागमती", "rural_municipality", 7),
        ("Mahankal", "महाङ्काल", "rural_municipality", 6),
    ],
    "Makwanpur": [
        ("Hetauda", "हेटौंडा", "sub_metropolitan", 19),
        ("Thaha", "थाहा", "municipality", 12),
        ("Bagmati", "बागमती", "rural_municipality", 9),
        ("Bakaiya", "बकैया", "rural_municipality", 12),
        ("Bhimphedi", "भीमफेदी", "rural_municipality", 9),
        ("Indrasarowar", "इन्द्रसरोवर", "rural_municipality", 5),
        ("Kailash", "कैलाश", "rural_municipality", 10),
        ("Makawanpurgadhi", "मकवानपुरगढी", "rural_municipality", 8),
        ("Manahari", "मनहरी", "rural_municipality", 9),
        ("Raksirang", "राक्सिराङ्ग", "rural_municipality", 9),
    ],
    "Nuwakot": [
        ("Belkotgadhi", "बेलकोटगढी", "municipality", 13),
        ("Bidur", "विदुर", "municipality", 13),
        ("Dupcheshwar", "दुप्चेश्वर", "rural_municipality", 7),
        ("Kakani", "ककनी", "rural_municipality", 8),
        ("Kispang", "किस्पाङ", "rural_municipality", 5),
        ("Likhu", "लिखु", "rural_municipality", 6),
        ("Meghang", "म्यगङ", "rural_municipality", 6),
        ("Panchakanya", "पञ्चकन्या", "rural_municipality", 5),
        ("Shivapuri", "शिवपुरी", "rural_municipality", 8),
        ("Suryagadhi", "सूर्यगढी", "rural_municipality", 5),
        ("Tadi", "तादी", "rural_municipality", 6),
        ("Tarkeshwar", "तारकेश्वर", "rural_municipality", 6),
    ],
    "Ramechhap": [
        ("Manthali", "मन्थली", "municipality", 14),
        ("Ramechhap", "रामेछाप", "municipality", 9),
        ("Doramba", "दोरम्बा", "rural_municipality", 7),
        ("Gokulganga", "गोकुलगङ्गा", "rural_municipality", 6),
        ("Khandadevi", "खाँडादेवी", "rural_municipality", 9),
        ("Likhu Tamakoshi", "लिखु तामाकोशी", "rural_municipality", 6),
        ("Sunapati", "सुनापती", "rural_municipality", 5),
        ("Umakunda", "उमाकुण्ड", "rural_municipality", 7),
    ],
    "Rasuwa": [
        ("Gosaikunda", "गोसाईकुण्ड", "rural_municipality", 6),
        ("Kalika", "कालिका", "rural_municipality", 5),
        ("Naukunda", "नौकुण्ड", "rural_municipality", 6),
        ("Parbatikunda", "पार्वतीकुण्ड", "rural_municipality", 5),
        ("Uttargaya", "उत्तरगया", "rural_municipality", 5),
    ],
    "Sindhuli": [
        ("Kamalamai", "कमलामाई", "municipality", 14),
        ("Dudhauli", "दुधौली", "municipality", 14),
        ("Golanjor", "गोलन्जोर", "rural_municipality", 7),
        ("Ghyanglekh", "घ्याङलेख", "rural_municipality", 5),
        ("Hariharpurgadhi", "हरिहरपुरगढी", "rural_municipality", 7),
        ("Marin", "मरिण", "rural_municipality", 6),
        ("Phikkal", "फिक्कल", "rural_municipality", 6),
        ("Sunkoshi", "सुनकोशी", "rural_municipality", 7),
        ("Tinpatan", "तीनपाटन", "rural_municipality", 9),
    ],
    "Sindhupalchok": [
        ("Chautara Sangachokgadhi", "चौतारा साँगाचोकगढी", "municipality", 14),
        ("Melamchi", "मेलम्ची", "municipality", 13),
        ("Barhabise", "बाह्रबिसे", "municipality", 9),
        ("Balephi", "बलेफी", "rural_municipality", 8),
        ("Bhotekoshi", "भोटेकोशी", "rural_municipality", 5),
        ("Helambu", "हेलम्बु", "rural_municipality", 7),
        ("Indrawati", "इन्द्रावती", "rural_municipality", 12),
        ("Jugal", "जुगल", "rural_municipality", 7),
        ("Lisankhu Pakhar", "लिसंखु पाखर", "rural_municipality", 7),
        ("Panchpokhari Thangpal", "पञ्चपोखरी थाङपाल", "rural_municipality", 8),
        ("Sunkoshi", "सुनकोशी", "rural_municipality", 5),
        ("Tripurasundari", "त्रिपुरासुन्दरी", "rural_municipality", 5),
    ],
    
    # ========== GANDAKI PROVINCE ==========
    "Baglung": [
        ("Baglung", "बागलुङ", "municipality", 14),
        ("Dhorpatan", "ढोरपाटन", "municipality", 9),
        ("Galkot", "गल्कोट", "municipality", 11),
        ("Jaimuni", "जैमिनी", "municipality", 10),
        ("Bareng", "बरेङ", "rural_municipality", 5),
        ("Khathekhola", "काठेखोला", "rural_municipality", 7),
        ("Nisikhola", "निसीखोला", "rural_municipality", 7),
        ("Taman Khola", "तमानखोला", "rural_municipality", 6),
        ("Tara Khola", "ताराखोला", "rural_municipality", 5),
        ("Badigad", "बडिगाड", "rural_municipality", 10),
    ],
    "Gorkha": [
        ("Gorkha", "गोरखा", "municipality", 14),
        ("Palungtar", "पालुङटार", "municipality", 10),
        ("Shahid Lakhan", "शहिद लखन", "rural_municipality", 9),
        ("Siranchowk", "सिरानचोक", "rural_municipality", 8),
        ("Ajirkot", "अजिरकोट", "rural_municipality", 5),
        ("Aarughat", "आरुघाट", "rural_municipality", 10),
        ("Gandaki", "गण्डकी", "rural_municipality", 8),
        ("Chum Nubri", "चुमनुब्री", "rural_municipality", 7),
        ("Dharche", "धार्चे", "rural_municipality", 7),
        ("Bhimsen Thapa", "भिमसेनथापा", "rural_municipality", 8),
        ("Sahid Lakhan", "शहिद लखन", "rural_municipality", 9),
    ],
    "Kaski": [
        ("Pokhara", "पोखरा", "metropolitan", 33),
        ("Annapurna", "अन्नपूर्ण", "rural_municipality", 11),
        ("Machhapuchchhre", "माछापुच्छ्रे", "rural_municipality", 9),
        ("Madi", "मादी", "rural_municipality", 12),
        ("Rupa", "रूपा", "rural_municipality", 7),
    ],
    "Lamjung": [
        ("Besishahar", "बेसीशहर", "municipality", 11),
        ("Madhya Nepal", "मध्य नेपाल", "municipality", 10),
        ("Rainas", "राईनास", "municipality", 8),
        ("Sundarbazar", "सुन्दरबजार", "municipality", 9),
        ("Kwholasothar", "क्व्होलासोथार", "rural_municipality", 9),
        ("Dudhpokhari", "दुधपोखरी", "rural_municipality", 6),
        ("Dordi", "दोर्दी", "rural_municipality", 9),
        ("Marsyangdi", "मर्स्याङदी", "rural_municipality", 9),
    ],
    "Manang": [
        ("Chame", "चामे", "rural_municipality", 5),
        ("Narshon", "नार्शोङ", "rural_municipality", 5),
        ("Narpa Bhumi", "नार्पा भूमि", "rural_municipality", 5),
        ("Manang Ngisyang", "मनाङ ङिस्याङ", "rural_municipality", 9),
    ],
    "Mustang": [
        ("Gharapjhong", "घरपझोङ", "rural_municipality", 5),
        ("Thasang", "थासाङ", "rural_municipality", 5),
        ("Barghung Muktikshetra", "बारागुङ मुक्तिक्षेत्र", "rural_municipality", 5),
        ("Lomanthang", "लोमन्थाङ", "rural_municipality", 5),
        ("Lo-Ghekar Damodarkunda", "लो-घेकर दामोदरकुण्ड", "rural_municipality", 5),
    ],
    "Myagdi": [
        ("Beni", "बेनी", "municipality", 10),
        ("Annapurna", "अन्नपूर्ण", "rural_municipality", 8),
        ("Dhaulagiri", "धौलागिरी", "rural_municipality", 7),
        ("Mangala", "मंगला", "rural_municipality", 6),
        ("Malika", "मालिका", "rural_municipality", 7),
        ("Raghuganga", "रघुगंगा", "rural_municipality", 6),
    ],
    "Nawalpur": [
        ("Kawasoti", "कावासोती", "municipality", 17),
        ("Gaindakot", "गैंडाकोट", "municipality", 18),
        ("Devchuli", "देवचुली", "municipality", 17),
        ("Madhyabindu", "मध्यबिन्दु", "municipality", 15),
        ("Baudikali", "बौदीकाली", "rural_municipality", 6),
        ("Bulingtar", "बुलिङटार", "rural_municipality", 6),
        ("Binayi Tribeni", "विनयी त्रिवेणी", "rural_municipality", 8),
        ("Hupsekot", "हुप्सेकोट", "rural_municipality", 5),
    ],
    "Parbat": [
        ("Kushma", "कुश्मा", "municipality", 14),
        ("Phalewas", "फलेवास", "municipality", 11),
        ("Jaljala", "जलजला", "rural_municipality", 6),
        ("Painyu", "पैयूं", "rural_municipality", 7),
        ("Mahashila", "महाशिला", "rural_municipality", 6),
        ("Modi", "मोदी", "rural_municipality", 8),
        ("Bihadi", "विहादी", "rural_municipality", 6),
    ],
    "Syangja": [
        ("Galyang", "गल्याङ", "municipality", 11),
        ("Chapakot", "चापाकोट", "municipality", 10),
        ("Putalibazar", "पुतलीबजार", "municipality", 14),
        ("Bhirkot", "भीरकोट", "municipality", 9),
        ("Waling", "वालिङ", "municipality", 14),
        ("Arjun Chaupari", "अर्जुन चौपारी", "rural_municipality", 6),
        ("Aandhikhola", "आँधीखोला", "rural_municipality", 6),
        ("Kaligandaki", "कालीगण्डकी", "rural_municipality", 7),
        ("Fedikhola", "फेदीखोला", "rural_municipality", 5),
        ("Harinas", "हरिनास", "rural_municipality", 7),
        ("Biruwa", "बिरुवा", "rural_municipality", 8),
    ],
    "Tanahun": [
        ("Bhanu", "भानु", "municipality", 13),
        ("Bhimad", "भिमाद", "municipality", 9),
        ("Byas", "व्यास", "municipality", 14),
        ("Shuklagandaki", "शुक्लागण्डकी", "municipality", 12),
        ("Anbu Khaireni", "आँबुखैरेनी", "rural_municipality", 6),
        ("Devghat", "देवघाट", "rural_municipality", 5),
        ("Bandipur", "बन्दीपुर", "rural_municipality", 6),
        ("Rishing", "ऋषिङ", "rural_municipality", 8),
        ("Ghiring", "घिरिङ", "rural_municipality", 5),
        ("Myagde", "म्याग्दे", "rural_municipality", 6),
    ],
    
    # ========== LUMBINI PROVINCE ==========
    "Arghakhanchi": [
        ("Sandhikharka", "सन्धिखर्क", "municipality", 12),
        ("Sitganga", "सीतगंगा", "municipality", 14),
        ("Bhumikasthan", "भूमिकास्थान", "municipality", 10),
        ("Chhatradev", "छत्रदेव", "rural_municipality", 6),
        ("Malarani", "मालारानी", "rural_municipality", 6),
        ("Panini", "पाणिनी", "rural_municipality", 6),
    ],
    "Banke": [
        ("Nepalgunj", "नेपालगञ्ज", "sub_metropolitan", 23),
        ("Kohalpur", "कोहलपुर", "municipality", 15),
        ("Rapti Sonari", "राप्ती सोनारी", "rural_municipality", 9),
        ("Narainapur", "नरैनापुर", "rural_municipality", 6),
        ("Duduwa", "डुडुवा", "rural_municipality", 6),
        ("Janaki", "जानकी", "rural_municipality", 6),
        ("Khajura", "खजुरा", "rural_municipality", 8),
        ("Baijanath", "बैजनाथ", "rural_municipality", 8),
    ],
    "Bardiya": [
        ("Gulariya", "गुलरिया", "municipality", 12),
        ("Madhuwan", "मधुवन", "municipality", 9),
        ("Rajapur", "राजापुर", "municipality", 10),
        ("Thakurbaba", "ठाकुरबाबा", "municipality", 9),
        ("Bansgadhi", "बाँसगढी", "municipality", 9),
        ("Barbardiya", "बारबर्दिया", "municipality", 11),
        ("Badhaiyatal", "बढैयाताल", "rural_municipality", 9),
        ("Geruwa", "गेरुवा", "rural_municipality", 6),
    ],
    "Dang": [
        ("Ghorahi", "घोराही", "sub_metropolitan", 19),
        ("Tulsipur", "तुलसीपुर", "sub_metropolitan", 19),
        ("Lamahi", "लमही", "municipality", 9),
        ("Gadhawa", "गढवा", "rural_municipality", 8),
        ("Rajpur", "राजपुर", "rural_municipality", 7),
        ("Shantinagar", "शान्तिनगर", "rural_municipality", 7),
        ("Rapti", "राप्ती", "rural_municipality", 9),
        ("Banglachuli", "बंगलाचुली", "rural_municipality", 8),
        ("Dangisharan", "दंगीशरण", "rural_municipality", 7),
        ("Babai", "बबई", "rural_municipality", 7),
    ],
    "Eastern Rukum": [
        ("Bhume", "भूमे", "rural_municipality", 9),
        ("Sisne", "सिस्ने", "rural_municipality", 7),
        ("Putha Uttarganga", "पुथा उत्तरगंगा", "rural_municipality", 14),
    ],
    "Gulmi": [
        ("Musikot", "मुसिकोट", "municipality", 13),
        ("Resunga", "रेसुंगा", "municipality", 14),
        ("Isma", "ईस्मा", "rural_municipality", 6),
        ("Kaligandaki", "कालीगण्डकी", "rural_municipality", 7),
        ("Gulmidarbar", "गुल्मीदरबार", "rural_municipality", 7),
        ("Satyawati", "सत्यवती", "rural_municipality", 8),
        ("Chandrakot", "चन्द्रकोट", "rural_municipality", 8),
        ("Ruru", "रुरु", "rural_municipality", 6),
        ("Chatrakot", "छत्रकोट", "rural_municipality", 6),
        ("Dhurkot", "धुर्कोट", "rural_municipality", 6),
        ("Madane", "मदाने", "rural_municipality", 6),
        ("Malika", "मालिका", "rural_municipality", 8),
    ],
    "Kapilvastu": [
        ("Kapilvastu", "कपिलवस्तु", "municipality", 12),
        ("Banganga", "बाणगंगा", "municipality", 11),
        ("Buddhabhumi", "बुद्धभूमि", "municipality", 10),
        ("Shivaraj", "शिवराज", "municipality", 11),
        ("Krishnanagar", "कृष्णनगर", "municipality", 12),
        ("Maharajgunj", "महाराजगंज", "municipality", 11),
        ("Mayadevi", "मायादेवी", "rural_municipality", 8),
        ("Yashodhara", "यशोधरा", "rural_municipality", 5),
        ("Suddhodhan", "शुद्धोधन", "rural_municipality", 5),
        ("Bijaynagar", "विजयनगर", "rural_municipality", 7),
    ],
    "Nawalparasi West": [
        ("Bardaghat", "बर्दघाट", "municipality", 16),
        ("Ramgram", "रामग्राम", "municipality", 18),
        ("Sunwal", "सुनवल", "municipality", 13),
        ("Susta", "सुस्ता", "rural_municipality", 5),
        ("Palhinandan", "पाल्हीनन्दन", "rural_municipality", 6),
        ("Pratappur", "प्रतापपुर", "rural_municipality", 9),
        ("Sarawal", "सरावल", "rural_municipality", 7),
    ],
    "Palpa": [
        ("Tansen", "तानसेन", "municipality", 14),
        ("Rampur", "रामपुर", "municipality", 10),
        ("Rainadevi Chhahara", "रैनादेवी छहरा", "rural_municipality", 8),
        ("Ripdikot", "रिब्दीकोट", "rural_municipality", 6),
        ("Bagnaskali", "बगनासकाली", "rural_municipality", 9),
        ("Rambha", "रम्भा", "rural_municipality", 7),
        ("Purbakhola", "पूर्वखोला", "rural_municipality", 5),
        ("Nisdi", "निस्दी", "rural_municipality", 7),
        ("Mathagadhi", "माथागढी", "rural_municipality", 5),
        ("Tinau", "तिनाउ", "rural_municipality", 6),
    ],
    "Pyuthan": [
        ("Pyuthan", "प्यूठान", "municipality", 10),
        ("Sworgadwari", "स्वर्गद्वारी", "municipality", 9),
        ("Gaumukhi", "गौमुखी", "rural_municipality", 6),
        ("Mandavi", "माण्डवी", "rural_municipality", 5),
        ("Sarumarani", "सरुमारानी", "rural_municipality", 5),
        ("Mallarani", "मल्लरानी", "rural_municipality", 5),
        ("Naubahini", "नौवहिनी", "rural_municipality", 6),
        ("Jhimruk", "झिमरुक", "rural_municipality", 5),
        ("Airawati", "ऐरावती", "rural_municipality", 6),
    ],
    "Rolpa": [
        ("Rolpa", "रोल्पा", "municipality", 10),
        ("Triveni", "त्रिवेणी", "rural_municipality", 5),
        ("Paribartan", "परिवर्तन", "rural_municipality", 6),
        ("Lungri", "लुङग्री", "rural_municipality", 5),
        ("Sunchhahari", "सुनछहरी", "rural_municipality", 5),
        ("Thawang", "थवाङ", "rural_municipality", 5),
        ("Madi", "माडी", "rural_municipality", 6),
        ("Gangadev", "गंगादेव", "rural_municipality", 6),
        ("Runtigadhi", "रुन्टीगढी", "rural_municipality", 9),
        ("Sunil Smriti", "सुनिल स्मृति", "rural_municipality", 7),
    ],
    "Rupandehi": [
        ("Butwal", "बुटवल", "sub_metropolitan", 19),
        ("Siddharthanagar", "सिद्धार्थनगर", "municipality", 13),
        ("Devdaha", "देवदह", "municipality", 12),
        ("Lumbini Sanskritik", "लुम्बिनी सांस्कृतिक", "municipality", 13),
        ("Sainamaina", "सैनामैना", "municipality", 11),
        ("Tilottama", "तिलोत्तमा", "municipality", 17),
        ("Gaidahawa", "गैडहवा", "rural_municipality", 9),
        ("Kanchan", "कञ्चन", "rural_municipality", 6),
        ("Kotahimai", "कोटहीमाई", "rural_municipality", 7),
        ("Marchawari", "मर्चवारी", "rural_municipality", 7),
        ("Mayadevi", "मायादेवी", "rural_municipality", 8),
        ("Omsatiya", "ओमसतिया", "rural_municipality", 6),
        ("Rohini", "रोहिणी", "rural_municipality", 7),
        ("Sammarimai", "सम्मरीमाई", "rural_municipality", 6),
        ("Siyari", "सियारी", "rural_municipality", 7),
        ("Suddhodhan", "शुद्धोधन", "rural_municipality", 6),
    ],
    "Western Rukum": [
        ("Musikot", "मुसिकोट", "municipality", 14),
        ("Chaurjahari", "चौरजहारी", "municipality", 8),
        ("Aathbiskot", "आठबिसकोट", "municipality", 9),
        ("Banphikot", "बाँफिकोट", "rural_municipality", 6),
        ("Tribeni", "त्रिवेणी", "rural_municipality", 6),
        ("Sani Bheri", "सानी भेरी", "rural_municipality", 7),
    ],
    
    # ========== KARNALI PROVINCE ==========
    "Dailekh": [
        ("Narayan", "नारायण", "municipality", 11),
        ("Dullu", "दुल्लु", "municipality", 13),
        ("Aathbis", "आठबीस", "municipality", 9),
        ("Chamunda Bindrasaini", "चामुण्डा बिन्द्रासैनी", "municipality", 9),
        ("Thantikandh", "ठाँटीकाँध", "rural_municipality", 6),
        ("Bhairabi", "भैरवी", "rural_municipality", 7),
        ("Mahabu", "महाबु", "rural_municipality", 6),
        ("Naumule", "नौमुले", "rural_municipality", 8),
        ("Dungeshwar", "डुंगेश्वर", "rural_municipality", 6),
        ("Gurans", "गुराँस", "rural_municipality", 8),
        ("Bhagwatimai", "भगवतीमाई", "rural_municipality", 7),
    ],
    "Dolpa": [
        ("Thuli Bheri", "ठूली भेरी", "municipality", 11),
        ("Tripurasundari", "त्रिपुरासुन्दरी", "municipality", 11),
        ("Dolpo Buddha", "डोल्पो बुद्ध", "rural_municipality", 6),
        ("She Phoksundo", "शे फोक्सुन्डो", "rural_municipality", 9),
        ("Jagadulla", "जगदुल्ला", "rural_municipality", 6),
        ("Mudkechula", "मुड्केचुला", "rural_municipality", 9),
        ("Kaike", "काईके", "rural_municipality", 7),
        ("Chharka Tangsong", "छार्का ताङसोङ", "rural_municipality", 6),
    ],
    "Humla": [
        ("Simkot", "सिमकोट", "rural_municipality", 8),
        ("Namkha", "नाम्खा", "rural_municipality", 6),
        ("Kharpunath", "खार्पुनाथ", "rural_municipality", 5),
        ("Sarkegad", "सर्केगाड", "rural_municipality", 8),
        ("Chankheli", "चंखेली", "rural_municipality", 6),
        ("Adanchuli", "अदानचुली", "rural_municipality", 6),
        ("Tanjakot", "ताँजाकोट", "rural_municipality", 5),
    ],
    "Jajarkot": [
        ("Bheri", "भेरी", "municipality", 13),
        ("Chhedagad", "छेडागाड", "municipality", 13),
        ("Nalgad", "नलगाड", "municipality", 13),
        ("Junichande", "जुनीचाँदे", "rural_municipality", 11),
        ("Kushe", "कुशे", "rural_municipality", 9),
        ("Barekot", "बारेकोट", "rural_municipality", 9),
        ("Shivalaya", "शिवालय", "rural_municipality", 9),
    ],
    "Jumla": [
        ("Chandannath", "चन्दननाथ", "municipality", 10),
        ("Kankasundari", "कनकासुन्दरी", "rural_municipality", 6),
        ("Sinja", "सिन्जा", "rural_municipality", 6),
        ("Hima", "हिमा", "rural_municipality", 7),
        ("Tila", "तिला", "rural_municipality", 9),
        ("Guthichaur", "गुठिचौर", "rural_municipality", 5),
        ("Tatopani", "तातोपानी", "rural_municipality", 8),
        ("Patarasi", "पातारासी", "rural_municipality", 7),
    ],
    "Kalikot": [
        ("Khandachakra", "खाँडाचक्र", "municipality", 11),
        ("Raskot", "रास्कोट", "municipality", 9),
        ("Tilagufa", "तिलागुफा", "municipality", 11),
        ("Palata", "पलाता", "rural_municipality", 9),
        ("Pachaljharana", "पचालझरना", "rural_municipality", 9),
        ("Sanni Triveni", "सान्नी त्रिवेणी", "rural_municipality", 7),
        ("Narharinath", "नरहरिनाथ", "rural_municipality", 9),
        ("Shubha Kalika", "शुभ कालिका", "rural_municipality", 5),
        ("Mahawai", "महावै", "rural_municipality", 7),
    ],
    "Mugu": [
        ("Chhayanath Rara", "छायाँनाथ रारा", "municipality", 14),
        ("Mugum Karmarong", "मुगुम कार्मारोङ", "rural_municipality", 9),
        ("Soru", "सोरु", "rural_municipality", 11),
        ("Khatyad", "खत्याड", "rural_municipality", 11),
    ],
    "Salyan": [
        ("Shaarda", "शारदा", "municipality", 15),
        ("Bagchaur", "बागचौर", "municipality", 12),
        ("Bangad Kupinde", "बनगाड कुपिण्डे", "municipality", 12),
        ("Kalimati", "कालिमाटी", "rural_municipality", 7),
        ("Tribeni", "त्रिवेणी", "rural_municipality", 6),
        ("Kapurkot", "कपुरकोट", "rural_municipality", 6),
        ("Chatreshwari", "छत्रेश्वरी", "rural_municipality", 6),
        ("Dhorchaur", "ढोरचौर", "rural_municipality", 5),
        ("Kumakh", "कुमाख", "rural_municipality", 7),
        ("Darma", "दार्मा", "rural_municipality", 7),
    ],
    "Surkhet": [
        ("Birendranagar", "वीरेन्द्रनगर", "municipality", 16),
        ("Bheriganga", "भेरीगंगा", "municipality", 13),
        ("Gurbhakot", "गुर्भाकोट", "municipality", 14),
        ("Panchpuri", "पञ्चपुरी", "municipality", 11),
        ("Lekbeshi", "लेकबेशी", "municipality", 10),
        ("Chaukune", "चौकुने", "rural_municipality", 8),
        ("Barahatal", "बराहताल", "rural_municipality", 9),
        ("Chingad", "चिंगाड", "rural_municipality", 6),
        ("Simta", "सिम्ता", "rural_municipality", 9),
    ],
    
    # ========== SUDURPASHCHIM PROVINCE ==========
    "Achham": [
        ("Mangalsen", "मंगलसेन", "municipality", 14),
        ("Kamalbazar", "कमलबजार", "municipality", 9),
        ("Sanphebagar", "साँफेबगर", "municipality", 13),
        ("Panchadewal Binayak", "पञ्चदेवल विनायक", "municipality", 9),
        ("Ramaroshan", "रामारोशन", "rural_municipality", 7),
        ("Chaurpati", "चौरपाटी", "rural_municipality", 7),
        ("Turmakhand", "तुर्माखाँद", "rural_municipality", 6),
        ("Mellekh", "मेल्लेख", "rural_municipality", 5),
        ("Dhakari", "ढकारी", "rural_municipality", 8),
        ("Bannigadhi Jayagadh", "बान्नीगढी जयगढ", "rural_municipality", 6),
    ],
    "Baitadi": [
        ("Dasharathchand", "दशरथचन्द", "municipality", 11),
        ("Patan", "पाटन", "municipality", 10),
        ("Melauli", "मेलौली", "municipality", 9),
        ("Purchaudi", "पुर्चौडी", "municipality", 10),
        ("Surma", "सुर्मा", "rural_municipality", 5),
        ("Sigas", "सिगास", "rural_municipality", 6),
        ("Shivanath", "शिवनाथ", "rural_municipality", 6),
        ("Pancheshwar", "पञ्चेश्वर", "rural_municipality", 6),
        ("Dogdakedar", "डोगडाकेदार", "rural_municipality", 7),
        ("Dilasaini", "डीलासैनी", "rural_municipality", 7),
    ],
    "Bajhang": [
        ("Jaya Prithvi", "जया पृथ्वी", "municipality", 11),
        ("Bungal", "बुंगल", "municipality", 11),
        ("Talkot", "तलकोट", "rural_municipality", 5),
        ("Masta", "मष्टा", "rural_municipality", 7),
        ("Khaptadchhanna", "खप्तड छान्ना", "rural_municipality", 5),
        ("Thalara", "थलारा", "rural_municipality", 9),
        ("Bitthadchir", "बित्थडचिर", "rural_municipality", 9),
        ("Surma", "सुर्मा", "rural_municipality", 5),
        ("Chhabispathibhera", "छबिस पाथिभेरा", "rural_municipality", 6),
        ("Durgathali", "दुर्गाथली", "rural_municipality", 6),
        ("Kedarsyu", "केदारस्युँ", "rural_municipality", 7),
        ("Saipal", "साइपाल", "rural_municipality", 5),
    ],
    "Bajura": [
        ("Badimalika", "बडीमालिका", "municipality", 9),
        ("Triveni", "त्रिवेणी", "municipality", 9),
        ("Budhiganga", "बुढीगंगा", "municipality", 10),
        ("Budhinanda", "बुढीनन्दा", "municipality", 10),
        ("Gaumul", "गौमुल", "rural_municipality", 6),
        ("Pandav Gupha", "पाण्डव गुफा", "rural_municipality", 6),
        ("Swamikartik", "स्वामीकार्तिक", "rural_municipality", 5),
        ("Chhededaha", "छेडेदह", "rural_municipality", 7),
        ("Himali", "हिमाली", "rural_municipality", 7),
    ],
    "Dadeldhura": [
        ("Amargadhi", "अमरगढी", "municipality", 11),
        ("Parshuram", "परशुराम", "municipality", 12),
        ("Aalital", "आलिताल", "rural_municipality", 8),
        ("Bhageshwar", "भागेश्वर", "rural_municipality", 5),
        ("Navadurga", "नवदुर्गा", "rural_municipality", 5),
        ("Ajayameru", "अजयमेरु", "rural_municipality", 6),
        ("Ganyapdhura", "गन्यापधुरा", "rural_municipality", 5),
    ],
    "Darchula": [
        ("Mahakali", "महाकाली", "municipality", 9),
        ("Shailyashikhar", "शैल्यशिखर", "municipality", 9),
        ("Malikarjun", "मालिकार्जुन", "rural_municipality", 7),
        ("Apihimal", "अपिहिमाल", "rural_municipality", 6),
        ("Duhun", "दुहुँ", "rural_municipality", 5),
        ("Naugad", "नौगाड", "rural_municipality", 6),
        ("Marma", "मर्मा", "rural_municipality", 5),
        ("Lekam", "लेकम", "rural_municipality", 6),
        ("Vyans", "व्याँस", "rural_municipality", 5),
    ],
    "Doti": [
        ("Dipayal Silgadhi", "दिपायल सिलगढी", "municipality", 9),
        ("Shikhar", "शिखर", "municipality", 11),
        ("Purbichauki", "पूर्वीचौकी", "rural_municipality", 7),
        ("Badikedar", "बडीकेदार", "rural_municipality", 5),
        ("Jorayal", "जोरायल", "rural_municipality", 6),
        ("Sayal", "सायल", "rural_municipality", 6),
        ("Aadarsha", "आदर्श", "rural_municipality", 7),
        ("K I Singh", "के आई सिंह", "rural_municipality", 7),
        ("Bogatan", "बोगटान", "rural_municipality", 7),
    ],
    "Kailali": [
        ("Dhangadhi", "धनगढी", "sub_metropolitan", 19),
        ("Lamki Chuha", "लम्की चुहा", "municipality", 10),
        ("Tikapur", "टीकापुर", "municipality", 14),
        ("Ghodaghodi", "घोडाघोडी", "municipality", 12),
        ("Bhajani", "भजनी", "municipality", 10),
        ("Godawari", "गोदावरी", "municipality", 12),
        ("Gauriganga", "गौरीगंगा", "municipality", 11),
        ("Janaki", "जानकी", "rural_municipality", 9),
        ("Bardagoriya", "बर्दगोरिया", "rural_municipality", 6),
        ("Mohanyal", "मोहन्याल", "rural_municipality", 7),
        ("Kailari", "कैलारी", "rural_municipality", 9),
        ("Joshipur", "जोशीपुर", "rural_municipality", 7),
        ("Chure", "चुरे", "rural_municipality", 5),
    ],
    "Kanchanpur": [
        ("Bhimdatta", "भीमदत्त", "municipality", 19),
        ("Punarbas", "पुनर्वास", "municipality", 11),
        ("Bedkot", "बेदकोट", "municipality", 10),
        ("Mahakali", "महाकाली", "municipality", 9),
        ("Shuklaphanta", "शुक्लाफाँटा", "municipality", 12),
        ("Belauri", "बेलौरी", "municipality", 10),
        ("Krishnapur", "कृष्णपुर", "municipality", 9),
        ("Laljhadi", "लालझाडी", "rural_municipality", 6),
        ("Beldandi", "बेलडाँडी", "rural_municipality", 5),
    ],
}


def load_all_753_municipalities():
    """Load all 753 municipalities into the database"""
    
    print("=" * 80)
    print("LOADING ALL 753 MUNICIPALITIES")
    print("=" * 80)
    
    total_created = 0
    total_updated = 0
    total_errors = 0
    missing_districts = []
    
    # Count total municipalities in data
    total_in_data = sum(len(municipalities) for municipalities in COMPLETE_MUNICIPALITY_DATA.values())
    print(f"\nTotal municipalities in data: {total_in_data}")
    
    for district_name, municipalities in COMPLETE_MUNICIPALITY_DATA.items():
        # Try to find the district
        district = District.objects.filter(name_en=district_name).first()
        
        if not district:
            # Special case: Nawalparasi East is stored as Nawalpur
            if district_name == "Nawalparasi East":
                district = District.objects.filter(name_en="Nawalpur").first()
            # Try partial matching for districts like "Eastern Rukum" or "Western Rukum"
            elif "Eastern" in district_name:
                base_name = district_name.replace("Eastern", "").strip()
                district = District.objects.filter(name_en__icontains=base_name).filter(name_en__icontains="East").first()
            elif "Western" in district_name:
                base_name = district_name.replace("Western", "").strip()
                district = District.objects.filter(name_en__icontains=base_name).filter(name_en__icontains="West").first()
        
        if not district:
            missing_districts.append(district_name)
            print(f"\n❌ District NOT found: {district_name} - Skipping {len(municipalities)} municipalities")
            total_errors += len(municipalities)
            continue
        
        print(f"\n✅ Processing {district_name} (Found as: {district.name_en})")
        
        for mun_data in municipalities:
            name_en, name_ne, mun_type, wards = mun_data
            
            # Map municipality types
            type_map = {
                'metropolitan': 'metropolitan',
                'sub_metropolitan': 'sub_metropolitan',
                'municipality': 'municipality',
                'rural_municipality': 'rural_municipality'
            }
            municipality_type = type_map.get(mun_type, 'rural_municipality')
            
            try:
                municipality, created = Municipality.objects.update_or_create(
                    district=district,
                    name_en=name_en,
                    defaults={
                        'name_ne': name_ne,
                        'municipality_type': municipality_type,
                        'total_wards': wards
                    }
                )
                
                if created:
                    total_created += 1
                    print(f"   ✅ Created: {name_en} ({municipality_type}, {wards} wards)")
                else:
                    total_updated += 1
                    print(f"   ✅ Updated: {name_en}")
            
            except Exception as e:
                total_errors += 1
                print(f"   ❌ Error: {name_en} - {str(e)}")
    
    # Final report
    print("\n" + "=" * 80)
    print("FINAL REPORT")
    print("=" * 80)
    print(f"Total municipalities in data: {total_in_data}")
    print(f"Created: {total_created}")
    print(f"Updated: {total_updated}")
    print(f"Errors: {total_errors}")
    print(f"Total processed: {total_created + total_updated}")
    
    if missing_districts:
        print(f"\n❌ Missing districts ({len(missing_districts)}):")
        for district in missing_districts:
            print(f"   - {district}")
    
    # Check final count in database
    db_count = Municipality.objects.count()
    print(f"\n📊 Total municipalities in database: {db_count}")
    
    if db_count == 753:
        print("\n🎉 SUCCESS! All 753 municipalities are now loaded!")
    else:
        print(f"\n⚠️  Still missing {753 - db_count} municipalities")


if __name__ == "__main__":
    load_all_753_municipalities()