# Generated by Django 4.2.7 on 2025-10-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateRegistrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=200)),
                ('position_level', models.CharField(max_length=50)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Candidate Registration Event',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_page_views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('total_candidates', models.IntegerField(default=0)),
                ('new_candidates', models.IntegerField(default=0)),
                ('approved_candidates', models.IntegerField(default=0)),
                ('avg_session_duration', models.FloatField(default=0)),
                ('bounce_rate', models.FloatField(default=0)),
                ('top_page', models.CharField(blank=True, max_length=500)),
                ('top_page_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Daily Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PopularPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, unique=True)),
                ('view_count', models.IntegerField(default=0)),
                ('unique_visitor_count', models.IntegerField(default=0)),
                ('last_viewed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-view_count'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('session_key', models.CharField(db_index=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_mobile', models.BooleanField(default=False)),
                ('browser', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'path'], name='analytics_p_timesta_cd14c8_idx'), models.Index(fields=['session_key', 'timestamp'], name='analytics_p_session_982099_idx')],
            },
        ),
    ]
