# Generated by Django 4.2.7 on 2025-09-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_add_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candidate',
            name='unique_user_candidate',
        ),
        migrations.RemoveConstraint(
            model_name='candidate',
            name='unique_ward_candidate',
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_mt_bio_ne',
            field=models.BooleanField(default=False, help_text='True if bio_ne is machine translated'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_mt_education_ne',
            field=models.BooleanField(default=False, help_text='True if education_ne is machine translated'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_mt_experience_ne',
            field=models.BooleanField(default=False, help_text='True if experience_ne is machine translated'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_mt_manifesto_ne',
            field=models.BooleanField(default=False, help_text='True if manifesto_ne is machine translated'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Verification Rejected')], default='pending', max_length=20),
        ),
    ]
