# Generated by Django 4.2.7 on 2025-09-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_add_bilingual_fields'),
        ('candidates', '0005_remove_verification_fields'),
    ]

    operations = [
    ]
