# Generated by Django 4.2.7 on 2025-09-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_merge_20250919_0114'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='candidate',
            name='candidates__verific_118207_idx',
        ),
    ]
