# Generated by Django 4.2.7 on 2025-09-19 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_candidate_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='date_of_birth',
        ),
    ]
