# Generated by Django 4.2.7 on 2025-09-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_candidate_admin_notes_candidate_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='position_level',
            field=models.CharField(choices=[('ward_chairperson', 'Ward Chairperson'), ('ward_member', 'Ward Member'), ('mayor', 'Mayor (Municipality/Metropolitan)'), ('chairperson', 'Chairperson (Rural Municipality)'), ('deputy_mayor', 'Deputy Mayor (Municipality/Metropolitan)'), ('vice_chairperson', 'Vice-Chairperson (Rural Municipality)'), ('provincial_assembly', 'Provincial Assembly Member'), ('house_of_representatives', 'House of Representatives Member'), ('national_assembly', 'National Assembly Member')], max_length=30),
        ),
    ]
