# Generated by Django 4.2.7 on 2025-09-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_update_position_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='position_level',
            field=models.CharField(choices=[('ward_chairperson', 'Ward Chairperson'), ('ward_member', 'Ward Member'), ('mayor_chairperson', 'Mayor/Chairperson'), ('deputy_mayor_vice_chairperson', 'Deputy Mayor/Vice Chairperson'), ('provincial_assembly', 'Provincial Assembly Member'), ('house_of_representatives', 'House of Representatives Member'), ('national_assembly', 'National Assembly Member')], max_length=35),
        ),
    ]
