# Generated by Django 4.2.7 on 2025-09-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_update_position_levels_final'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['status', 'province', 'district', 'municipality', 'ward_number'], name='ballot_location_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['status', 'position_level', 'province'], name='ballot_position_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['status', 'created_at'], name='status_created_idx'),
        ),
    ]
