# Generated by Django 4.2.7 on 2025-09-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_add_ballot_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='donation_description',
            field=models.CharField(blank=True, help_text='Brief description of what donations will be used for', max_length=200),
        ),
    ]
