# Generated by Django 4.2.7 on 2025-09-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_add_donation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='achievements_en',
            field=models.TextField(blank=True, help_text='Key achievements and accomplishments'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='achievements_ne',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidacy_document',
            field=models.FileField(blank=True, help_text='Official election declaration paper (confidential)', null=True, upload_to='verification_docs/candidacy/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='identity_document',
            field=models.FileField(blank=True, help_text="National ID/Citizenship/Driver's License (confidential)", null=True, upload_to='verification_docs/identity/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_mt_achievements_ne',
            field=models.BooleanField(default=False, help_text='True if achievements_ne is machine translated'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='Candidate has accepted terms and conditions'),
        ),
    ]
