# Generated by Django 4.2.7 on 2025-09-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0015_candidate_achievements_en_candidate_achievements_ne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='office',
            field=models.CharField(choices=[('federal', 'Federal'), ('provincial', 'Provincial'), ('municipal', 'Municipal'), ('ward', 'Ward')], default='municipal', help_text='Office level (Federal/Provincial/Municipal/Ward)', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position_level',
            field=models.CharField(choices=[('ward_chairperson', 'Ward Chairperson'), ('ward_member', 'Ward Member'), ('mayor_chairperson', 'Mayor/Chairperson'), ('deputy_mayor_vice_chairperson', 'Deputy Mayor/Vice Chairperson'), ('provincial_assembly', 'Provincial Assembly Member'), ('house_of_representatives', 'House of Representatives Member'), ('national_assembly', 'National Assembly Member')], help_text='Specific seat/position being contested', max_length=35, verbose_name='Seat'),
        ),
    ]
