# Generated by Django 4.2.7 on 2025-10-07 19:15

import candidates.models
import candidates.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0017_add_fulltext_search_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatepost',
            name='candidate',
        ),
        migrations.RemoveIndex(
            model_name='candidate',
            name='status_created_idx',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidacy_document',
            field=models.FileField(blank=True, help_text='Official election declaration paper (PDF/JPG/PNG, max 10MB, confidential)', null=True, upload_to='verification_docs/candidacy/%Y/%m/', validators=[candidates.validators.validate_file_size, candidates.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='identity_document',
            field=models.FileField(blank=True, help_text="National ID/Citizenship/Driver's License (PDF/JPG/PNG, max 10MB, confidential)", null=True, upload_to='verification_docs/identity/%Y/%m/', validators=[candidates.validators.validate_file_size, candidates.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile photo (JPG/PNG, max 5MB)', null=True, upload_to=candidates.models.candidate_photo_path, validators=[candidates.validators.validate_image_size, candidates.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ward_number',
            field=models.IntegerField(blank=True, help_text='Ward number (required for ward-level positions, must be valid for the selected municipality)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['status', '-created_at', 'full_name'], name='status_created_name_idx'),
        ),
        migrations.DeleteModel(
            name='CandidatePost',
        ),
    ]
