# Generated by Django 4.2.7 on 2025-10-12 20:29

import candidates.models
import candidates.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0019_standardize_position_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='office',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidacy_document',
            field=models.FileField(blank=True, help_text='Official election declaration paper (PDF/JPG/PNG, max 10MB, confidential)', null=True, upload_to='verification_docs/candidacy/%Y/%m/', validators=[candidates.validators.validate_file_size, candidates.validators.validate_file_extension, candidates.validators.validate_file_content_type]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='identity_document',
            field=models.FileField(blank=True, help_text="National ID/Citizenship/Driver's License (PDF/JPG/PNG, max 10MB, confidential)", null=True, upload_to='verification_docs/identity/%Y/%m/', validators=[candidates.validators.validate_file_size, candidates.validators.validate_file_extension, candidates.validators.validate_file_content_type]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile photo (JPG/PNG, max 5MB)', null=True, upload_to=candidates.models.candidate_photo_path, validators=[candidates.validators.validate_image_size, candidates.validators.validate_image_extension, candidates.validators.validate_file_content_type]),
        ),
    ]
