# Generated by Django 4.2.7 on 2025-10-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='last_verification_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
