# Generated by Django 4.2.7 on 2025-10-05 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(help_text='Name to identify this API key', max_length=100)),
                ('contact_email', models.EmailField(help_text='Contact email for this API key holder', max_length=254)),
                ('organization', models.CharField(blank=True, help_text='Organization using this API key', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('can_read', models.BooleanField(default=True, help_text='Can read public data')),
                ('can_write', models.BooleanField(default=False, help_text='Can write/modify data')),
                ('rate_limit', models.IntegerField(default=1000, help_text='Requests per hour allowed')),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('total_requests', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for this key', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this API key')),
                ('user', models.ForeignKey(blank=True, help_text='User who owns this API key (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKeyUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('response_status', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='api_auth.apikey')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['api_key', 'timestamp'], name='api_auth_ap_api_key_21d21e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key', 'is_active'], name='api_auth_ap_key_0b88f2_idx'),
        ),
    ]
