# Generated by Django 4.2.7 on 2025-09-12 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('name_ne', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='locations_p_code_008a2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_ne', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='locations.province')),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_ne', models.CharField(max_length=100)),
                ('municipality_type', models.CharField(choices=[('metropolitan', 'Metropolitan City'), ('sub_metropolitan', 'Sub-Metropolitan City'), ('municipality', 'Municipality'), ('rural_municipality', 'Rural Municipality')], max_length=20)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('total_wards', models.IntegerField(default=9)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='locations.district')),
            ],
            options={
                'verbose_name_plural': 'Municipalities',
                'ordering': ['name_en'],
                'indexes': [models.Index(fields=['district', 'municipality_type'], name='locations_m_distric_01739b_idx'), models.Index(fields=['code'], name='locations_m_code_0a114d_idx')],
                'unique_together': {('district', 'name_en')},
            },
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['province', 'name_en'], name='locations_d_provinc_200585_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['code'], name='locations_d_code_5f88ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('province', 'name_en')},
        ),
    ]
